Create CODE_OF_CONDUCT.md issue #4
dheerajkotwani/NewsUp pull request #7
Opened 2020-12-07 16:56 UTC by Tejas1510

@dheerajkotwani I have added the code which fixes issue #4

2020-12-07 18:00 UTC, atarax665 requested changes

2020-12-07 18:00 UTC, atarax665 commented on CODE_OF_CONDUCT.md
> +reported by contacting the project team at . All
```suggestion
reported by contacting the project team at dheeraj.kotwani41@gmail.com . All
```

2020-12-07 18:12 UTC, Tejas1510 commented
@atarax665 I have updated the code of Conduct with the requested Changes

2020-12-10 18:52 UTC, dheerajkotwani approved these changes

2020-12-10 18:52 UTC, merged

2020-12-10 19:05 UTC, Tejas1510 commented
@dheerajkotwani it would be very nice if you update my score in the leaderboard 
Thank you